#pragma once
//WINDOW CONSTANTS
#define WINDOW_WIDTH 800
#define WINDOW_HEIGHT 600

//PLAYER CONSTANTS
#define DEFAULT_POSITION 100

#define PLAYER_WIDTH 50
#define PLAYER_HEIGHT 50

#define PLAYER_VELOCITY 10

//BACKGROUND IMAGE CONSTANTS
#define IMG_WIDTH 128
#define IMG_HEIGHT 128

#define IMG_X ((WINDOW_WIDTH - IMG_WIDTH) / 2)
#define IMG_Y ((WINDOW_HEIGHT - IMG_HEIGHT) / 2)